// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/otp/otp_service.proto

package otp

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _otp_service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on SendOtpRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SendOtpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendOtpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SendOtpRequestMultiError,
// or nil if none found.
func (m *SendOtpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendOtpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = SendOtpRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SendOtpRequestMultiError(errors)
	}

	return nil
}

func (m *SendOtpRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *SendOtpRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// SendOtpRequestMultiError is an error wrapping multiple validation errors
// returned by SendOtpRequest.ValidateAll() if the designated constraints
// aren't met.
type SendOtpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendOtpRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendOtpRequestMultiError) AllErrors() []error { return m }

// SendOtpRequestValidationError is the validation error returned by
// SendOtpRequest.Validate if the designated constraints aren't met.
type SendOtpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendOtpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendOtpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendOtpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendOtpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendOtpRequestValidationError) ErrorName() string { return "SendOtpRequestValidationError" }

// Error satisfies the builtin error interface
func (e SendOtpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendOtpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendOtpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendOtpRequestValidationError{}

// Validate checks the field values on ConfirmOtpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConfirmOtpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfirmOtpRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConfirmOtpRequestMultiError, or nil if none found.
func (m *ConfirmOtpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfirmOtpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = ConfirmOtpRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for OtpCode

	if len(errors) > 0 {
		return ConfirmOtpRequestMultiError(errors)
	}

	return nil
}

func (m *ConfirmOtpRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *ConfirmOtpRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// ConfirmOtpRequestMultiError is an error wrapping multiple validation errors
// returned by ConfirmOtpRequest.ValidateAll() if the designated constraints
// aren't met.
type ConfirmOtpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfirmOtpRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfirmOtpRequestMultiError) AllErrors() []error { return m }

// ConfirmOtpRequestValidationError is the validation error returned by
// ConfirmOtpRequest.Validate if the designated constraints aren't met.
type ConfirmOtpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmOtpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmOtpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmOtpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmOtpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmOtpRequestValidationError) ErrorName() string {
	return "ConfirmOtpRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConfirmOtpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmOtpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmOtpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmOtpRequestValidationError{}

// Validate checks the field values on ConfirmOtpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConfirmOtpResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConfirmOtpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConfirmOtpResponseMultiError, or nil if none found.
func (m *ConfirmOtpResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConfirmOtpResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetEmailId()); err != nil {
		err = ConfirmOtpResponseValidationError{
			field:  "EmailId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConfirmOtpResponseMultiError(errors)
	}

	return nil
}

func (m *ConfirmOtpResponse) _validateUuid(uuid string) error {
	if matched := _otp_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ConfirmOtpResponseMultiError is an error wrapping multiple validation errors
// returned by ConfirmOtpResponse.ValidateAll() if the designated constraints
// aren't met.
type ConfirmOtpResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConfirmOtpResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConfirmOtpResponseMultiError) AllErrors() []error { return m }

// ConfirmOtpResponseValidationError is the validation error returned by
// ConfirmOtpResponse.Validate if the designated constraints aren't met.
type ConfirmOtpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConfirmOtpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConfirmOtpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConfirmOtpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConfirmOtpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConfirmOtpResponseValidationError) ErrorName() string {
	return "ConfirmOtpResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ConfirmOtpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConfirmOtpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConfirmOtpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConfirmOtpResponseValidationError{}
